name: 'Composite Action Info'
description: 'Display information about this composite action'

runs:
  using: "composite"
  steps:
    - name: 'Print Context Variables'
      shell: bash
      run: |
        #============================== Print Context Variables ==============================
        context_github='${{ toJSON(github) }}' || true
        echo '::group::github'
        echo "${context_github}"
        echo '::endgroup::'

        context_env='${{ toJSON(env) }}' || true
        echo '::group::env'
        echo "${context_env}"
        echo '::endgroup::'

        context_job='${{ toJSON(job) }}' || true
        echo '::group::job'
        echo "${context_job}"
        echo '::endgroup::'

        context_jobs='${{ toJSON(jobs) }}' || true
        echo '::group::jobs'
        echo "${context_jobs}"
        echo '::endgroup::'

        context_steps='${{ toJSON(steps) }}' || true
        echo '::group::steps'
        echo "${context_steps}"
        echo '::endgroup::'

        context_runner='${{ toJSON(runner) }}' || true
        echo '::group::runner'
        echo "${context_runner}"
        echo '::endgroup::'

        context_secrets='${{ toJSON(secrets) }}' || true
        echo '::group::secrets'
        echo "${context_secrets}"
        echo '::endgroup::'

        context_strategy='${{ toJSON(strategy) }}' || true
        echo '::group::strategy'
        echo "${context_strategy}"
        echo '::endgroup::'

        context_matrix='${{ toJSON(matrix) }}' || true
        echo '::group::matrix'
        echo "${context_matrix}"
        echo '::endgroup::'

        context_needs='${{ toJSON(needs) }}' || true
        echo '::group::needs'
        echo "${context_needs}"
        echo '::endgroup::'

        context_inputs='${{ toJSON(inputs) }}' || true
        echo '::group::inputs'
        echo "${context_inputs}"
        echo '::endgroup::'
    - name: 'Print JS Objects'
      uses: actions/github-script@v6
      with:
        script: |
          core.info('============================== Print JS Objects ==============================')

          core.info('::group::github')
          core.info(JSON.stringify(github, null, 4))
          core.info('::endgroup::')

          const contextAttrs = JSON.stringify(context, null, 4)
          core.info('::group::context')
          core.info(contextAttrs)
          core.info('::endgroup::')
          await core.summary.addRaw(`
          # context

          <details>
          <summary>Object Attributes</summary>

          \`\`\`json
          ${contextAttrs}
          \`\`\`

          </details>
          `).write()

          core.info('::group::core')
          core.info(JSON.stringify(core, null, 4))
          core.info('::endgroup::')

          core.info('::group::glob')
          core.info(JSON.stringify(glob, null, 4))
          core.info('::endgroup::')

          core.info('::group::io')
          core.info(JSON.stringify(io, null, 4))
          core.info('::endgroup::')

          core.info('::group::exec')
          core.info(JSON.stringify(exec, null, 4))
          core.info('::endgroup::')