name: 'Composite Action Info'
description: 'Display information about this composite action'

runs:
  using: "composite"
  steps:
    - name: 'Print Context Variables'
      shell: bash
      run: |
        #============================== Print Context Variables ==============================
        function print_variable {
          echo '::group::$1'
          echo "$2"
          echo '::endgroup::'
          {
          cat <<EOF
          <details>
          <summary>$1</summary>

          \`\`\`json
          $2
          \`\`\`

          </details>

          EOF
          } >> "$GITHUB_STEP_SUMMARY"
        }

        { 
          echo '# Context Variables'
          echo
        } >> "$GITHUB_STEP_SUMMARY"

        print_variable 'github' '${{ toJSON(github) }}'

        context_env='${{ toJSON(env) }}'
        echo '::group::env'
        echo "${context_env}"
        echo '::endgroup::'

        context_job='${{ toJSON(job) }}'
        echo '::group::job'
        echo "${context_job}"
        echo '::endgroup::'

        context_steps='${{ toJSON(steps) }}'
        echo '::group::steps'
        echo "${context_steps}"
        echo '::endgroup::'

        context_runner='${{ toJSON(runner) }}'
        echo '::group::runner'
        echo "${context_runner}"
        echo '::endgroup::'

        context_strategy='${{ toJSON(strategy) }}'
        echo '::group::strategy'
        echo "${context_strategy}"
        echo '::endgroup::'

        context_matrix='${{ toJSON(matrix) }}'
        echo '::group::matrix'
        echo "${context_matrix}"
        echo '::endgroup::'

        context_inputs='${{ toJSON(inputs) }}'
        echo '::group::inputs'
        echo "${context_inputs}"
        echo '::endgroup::'
    - name: 'Print JS Objects'
      uses: actions/github-script@v6
      with:
        script: |
          core.info('============================== Print JS Objects ==============================')

          core.info('::group::github')
          core.info(JSON.stringify(github, null, 4))
          core.info('::endgroup::')

          const contextAttrs = JSON.stringify(context, null, 4)
          core.info('::group::context')
          core.info(contextAttrs)
          core.info('::endgroup::')
          await core.summary.addRaw(`
          # JavaScript Objects

          <details>
          <summary>context</summary>

          \`\`\`json
          ${contextAttrs}
          \`\`\`

          </details>
          `).write()

          core.info('::group::core')
          core.info(JSON.stringify(core, null, 4))
          core.info('::endgroup::')

          core.info('::group::glob')
          core.info(JSON.stringify(glob, null, 4))
          core.info('::endgroup::')

          core.info('::group::io')
          core.info(JSON.stringify(io, null, 4))
          core.info('::endgroup::')

          core.info('::group::exec')
          core.info(JSON.stringify(exec, null, 4))
          core.info('::endgroup::')