name: 'Composite Action Info'
description: 'Display information about this composite action'

runs:
  using: "composite"
  steps:
    - name: 'Print Context Variables'
      shell: bash
      run: |
        #============================== Print Context Variables ==============================
        echo '::group::github'
        echo '${{ toJSON(github) }}'
        echo '::endgroup::'
    - name: 'Print JS Objects'
      uses: actions/github-script@v6
      with:
        script: |
          core.info('============================== Print JS Objects ==============================')

          core.info('::group::github')
          core.info(JSON.stringify(github, null, 4))
          core.info('::endgroup::')

          const contextAttrs = JSON.stringify(context, null, 4)
          core.info('::group::context')
          core.info(contextAttrs)
          core.info('::endgroup::')
          await core.summary.addRaw(`
          # context

          <details>
          <summary>Object Attributes</summary>

          \`\`\`json
          ${contextAttrs}
          \`\`\`

          </details>
          `).write()

          core.info('::group::core')
          core.info(JSON.stringify(core, null, 4))
          core.info('::endgroup::')

          core.info('::group::glob')
          core.info(JSON.stringify(glob, null, 4))
          core.info('::endgroup::')

          core.info('::group::io')
          core.info(JSON.stringify(io, null, 4))
          core.info('::endgroup::')

          core.info('::group::exec')
          core.info(JSON.stringify(exec, null, 4))
          core.info('::endgroup::')