name: 'Composite Action Info'
description: 'Display information about this composite action'

runs:
  using: "composite"
  steps: 
    - name: 'Display Info'
      uses: actions/github-script@v6
      with:
        script: |
          core.info('::group::context')
          core.info(JSON.stringify(context, null, 4))
          core.info('::endgroup::')