name: 'Test Workflow'

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  happy_path:
    name: 'Happy Path'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v3
      - name: 'Call Action'
        uses: './'